server:
  port: 8888

spring:
  application:
    name: config-server
  zipkin:
    enable: true
    base-url: http://localhost:9411
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}


